### ISSUE TITLE
Epic: User Profile for Admin App

### ISSUE THREAD

**Issue by dottorer** [buzzn/admin-app#124]
We need to provide a way for users of the Admins App (and also later Display App) to view and maintain their current account settings including name, email / password and privacy settings.

A design for this flow can be found here: https://buzzn-team.atlassian.net/wiki/display/DEV/Flow%3A+Updating+user+profile

Includes:

- [ ] #158 View user profile
- [ ] #160 Edit user profile
- [ ] #159 Picture for user profile
- [ ] #161 Change email address
- [ ] #162 Change password
