### ISSUE TITLE
EPIC: Admin app (AA) - first cut

### ISSUE THREAD

**Issue by dottorer** [buzzn/admin-app#54]
We are working on a new design for a admin app to help localpool powergivers / managers to view and manage all relevant information for their power takers. This is being designed in https://github.com/buzzn/ux/issues/28 

In this epic, we are building out the profile_app to evolve into a full admin console. This includes the following individual tickets in priority order:

- [x] #79  / #112 - Overview of powertaker
- [x] #56 - View and Edit bank data
- [x] #119 - Multiple Banks for Contracting Party 
- [x] #64 - List all other Contracts
- [x] #101 - Overview of all installed meters, registers and their readings 
- [x] #55 - Overview of localpool with members
- [x] #77 - User profile drop down menu
- [x] #78 - Display charts and metrics for local pool
